fix: don't call #at() on Arguments
It causes

    TypeError: args.at is not a function

Fixes: e62bc2a0f523 ("style: automatic fixes for new ESLint rules")
Signed-off-by: Kevin Locke <kevin@kevinlocke.name>